export const PATHS = Object.freeze({
  home: '/',
  login: '/login',
  register: '/register',
  jobs: '/jobs',
  jobDetails: (id = ':id') => `/jobs/${id}`,
  candidateDashboard: '/dashboard/candidate',
  candidateApplications: '/dashboard/candidate/applications',
  candidateProfile: '/dashboard/candidate/profile',
  recruiterDashboard: '/dashboard/recruiter',
  recruiterJobs: '/dashboard/recruiter/jobs',
  recruiterJobNew: '/dashboard/recruiter/jobs/new',
  recruiterCompany: '/dashboard/recruiter/company',
  recruiterJobEdit: (id = ':id') => `/dashboard/recruiter/jobs/${id}/edit`,
  recruiterJobApplicants: (id = ':id') => `/dashboard/recruiter/jobs/${id}/applicants`,
  adminDashboard: '/dashboard/admin',
  adminUsers: '/dashboard/admin/users',
  adminJobs: '/dashboard/admin/jobs',
  adminApplications: '/dashboard/admin/applications',
})
