const { describe, logo } = require('./data');

const company = (key, name, industry, location, color, description, perks, recruiterName, recruiterLocation, createdDaysAgo) => ({
  key,
  name,
  industry,
  location,
  website: `https://${name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-$/, '')}.test`,
  logoUrl: logo(name, color),
  description,
  perks,
  createdDaysAgo,
  recruiter: { name: recruiterName, location: recruiterLocation },
});

const companies = [
  company('codecrest', 'CodeCrest Technologies', 'IT Services & Web Development', 'Andheri, Mumbai, India', '0e7490',
    'CodeCrest builds websites and business software for retail, education and logistics clients across Mumbai and beyond. Our 70-person team works from an Andheri studio and values clean code, honest reviews and quick learning.',
    ['Health insurance for you and your family', 'Learning budget for courses and certifications'], 'Rohan Deshmukh', 'Mumbai, India', 130),
  company('marinedrive', 'Marine Drive Digital', 'Digital Product Studio', 'Powai, Mumbai, India', 'c2410c',
    'Marine Drive Digital is a Powai-based studio designing and building web products for fintech, media and consumer brands. We are a small team that likes shipping quickly and teaching each other.',
    ['Flexible hours and hybrid work', 'A mentor for every new joiner'], 'Neha Kulkarni', 'Mumbai, India', 125),
  company('nexora', 'Nexora Digital', 'Product Engineering', 'Pune, India', '4338ca',
    'Nexora designs and engineers software products for startups in India and Europe. Our 120-person team in Pune works in small, senior-led squads and releases every week.',
    ['Flexible work-from-home days', 'Annual learning allowance'], 'Aditya Joshi', 'Pune, India', 122),
  company('bluepeak', 'BluePeak Softwares', 'SaaS', 'Bangalore, India', '1d4ed8',
    'BluePeak makes analytics and workflow software used by retail and healthcare teams. We are headquartered in Bangalore, run a strong engineering culture and invest in mentoring.',
    ['Stock options for full-time roles', 'Home-office allowance'], 'Sneha Reddy', 'Bangalore, India', 118),
  company('marina', 'Marina Software Labs', 'EdTech', 'Chennai, India', '0f766e',
    'Marina Software Labs builds learning platforms used by more than 300,000 students. Our Chennai team blends product thinking with solid engineering and plenty of room to grow.',
    ['Paid certifications', 'Flexible hybrid schedule'], 'Karthik Subramanian', 'Chennai, India', 115),
  company('finhaven', 'FinHaven Systems', 'FinTech & Data', 'Hyderabad, India', '7c3aed',
    'FinHaven provides payments, lending and risk-analytics software to banks and NBFCs. Our Hyderabad hub brings data scientists, analysts and backend engineers together on one floor.',
    ['Health insurance and wellness benefits', 'Annual performance bonus'], 'Vikram Rao', 'Hyderabad, India', 112),
  company('securenet', 'SecureNet Cyber Solutions', 'Cybersecurity', 'New Delhi, India', 'be123c',
    'SecureNet protects banks, hospitals and government bodies with managed security services. Our Delhi security operations centre runs around the clock and trains every new analyst.',
    ['Sponsored security certifications', 'Health insurance'], 'Ananya Malhotra', 'New Delhi, India', 110),
  company('matrixbyte', 'Matrix Byte Labs', 'Enterprise Software', 'Gurgaon, India', '334155',
    'Matrix Byte Labs builds workflow and reporting software for insurers and banks. The Gurgaon team of 200 values clear ownership, steady releases and career growth.',
    ['Meal and commute benefits', 'Structured career growth plans'], 'Sandeep Chauhan', 'Gurgaon, India', 108),
  company('techtonic', 'Techtonic Systems', 'HR Technology', 'Noida, India', 'b45309',
    'Techtonic makes HR and payroll software for mid-size companies across India. Our Noida office is friendly, learning-first and proud of how many freshers have grown into leads here.',
    ['Referral bonuses', 'A friendly, learning-first culture'], 'Pooja Bhardwaj', 'Noida, India', 105),
  company('pixelbay', 'Pixelbay Studio', 'Web & Design Agency', 'Ahmedabad, India', 'db2777',
    'Pixelbay is an Ahmedabad agency that designs and builds websites and small web apps for D2C brands and manufacturers. Designers and developers sit together and ship fast.',
    ['Flexible working hours', 'Creative team offsites'], 'Kunal Patel', 'Ahmedabad, India', 100),
  company('pinkcity', 'PinkCity Infotech', 'IT Services', 'Jaipur, India', 'ea580c',
    'PinkCity Infotech delivers websites and booking software for tourism and hospitality businesses across Rajasthan. Many of our developers joined as interns and stayed.',
    ['Paid internships that convert to full-time roles', 'Festival bonuses'], 'Meera Rathore', 'Jaipur, India', 98),
  company('hooghly', 'Hooghly Commerce Tech', 'E-commerce Technology', 'Kolkata, India', '0369a1',
    'Hooghly Commerce Tech runs an online marketplace and seller tools serving eastern India. Our Kolkata engineers work on ordering, payments and delivery software.',
    ['Health insurance', 'Flexible leave for a healthy work-life balance'], 'Debashish Mukherjee', 'Kolkata, India', 95),
  company('tricity', 'Tricity Softworks', 'Software Products', 'Chandigarh, India', '15803d',
    'Tricity Softworks builds health and fitness apps used across North India. Based in Chandigarh, we are a product-first team that keeps meetings short and code reviews kind.',
    ['Hybrid work', 'Training and certification support'], 'Harpreet Singh', 'Chandigarh, India', 92),
  company('chinar', 'Chinar Tech Solutions', 'Software & IT Training', 'Srinagar, Kashmir, India', '047857',
    'Chinar Tech Solutions is a Srinagar software company building websites, e-commerce tools and business software for clients in Kashmir and beyond, and training the next generation of developers.',
    ['A free training programme for new joiners', 'A supportive, close-knit team'], 'Sameer Wani', 'Srinagar, India', 90),
  company('anywhere', 'Anywhere Labs', 'Remote-first SaaS', 'Remote, India', '4f46e5',
    'Anywhere Labs is a remote-first SaaS company with a team spread across India. We work asynchronously, write things down and value focus time.',
    ['Fully remote with a home-office stipend', 'Async-first, flexible working hours'], 'Ishaan Kapoor', 'Remote, India', 88),
];

const companyByKey = Object.fromEntries(companies.map((c) => [c.key, c]));

const ROLE = {
  web: {
    skills: ['html', 'css', 'javascript', 'responsive design', 'git'], extra: ['react', 'rest apis'],
    doingA: ['Build responsive websites and landing pages with HTML, CSS and JavaScript', 'Turn Figma designs into pixel-accurate, accessible pages', 'Fix bugs and improve page speed across browsers and devices'],
    doingB: ['Develop and maintain client websites, from small brochure sites to web apps', 'Work with designers to bring layouts to life with clean, semantic HTML and CSS', 'Add interactivity with JavaScript and keep everything working on mobile'],
    needs: ['Solid HTML, CSS and JavaScript fundamentals', 'Experience with responsive design (Flexbox/Grid) and Git', 'Attention to detail and clear communication'],
  },
  frontend: {
    skills: ['html', 'css', 'javascript', 'react', 'tailwind css', 'git'], extra: ['typescript', 'rest apis'],
    doingA: ['Build user interfaces with React and Tailwind CSS', 'Integrate REST APIs and manage application state', 'Create reusable components and keep the UI fast and accessible'],
    doingB: ['Turn designs into responsive React screens', 'Work with backend engineers to connect the UI to REST APIs', 'Write component tests and improve performance and accessibility'],
    needs: ['Strong JavaScript, HTML and CSS', 'Hands-on React (hooks, routing, state management)', 'Comfortable with Git and code reviews'],
  },
  react: {
    skills: ['react', 'javascript', 'redux', 'html', 'css', 'rest apis', 'git'], extra: ['typescript', 'testing library'],
    doingA: ['Develop and maintain React applications used by real customers', 'Build reusable components with hooks and clean state management', 'Work with designers and backend engineers to ship features'],
    doingB: ['Build new product screens in React with Redux or Context API', 'Consume REST APIs and handle loading, error and empty states properly', 'Review pull requests and keep the component library tidy'],
    needs: ['Good knowledge of React, JavaScript (ES6+) and REST APIs', 'Experience with Redux or the Context API', 'Understanding of performance and testing basics'],
  },
  backend: {
    skills: ['node.js', 'express.js', 'mongodb', 'sql', 'rest apis', 'git'], extra: ['docker', 'aws'],
    doingA: ['Design and build REST APIs and background jobs', 'Model data in SQL or MongoDB and keep queries fast', 'Write tests, monitor services and fix production issues'],
    doingB: ['Build secure, well-documented APIs for web and mobile apps', 'Design database schemas and optimise slow queries', 'Handle authentication, validation and error handling carefully'],
    needs: ['Strong backend fundamentals in Node.js or Python', 'Working knowledge of SQL and NoSQL databases', 'Understanding of authentication, REST design and Git'],
  },
  nodejs: {
    skills: ['node.js', 'express.js', 'mongodb', 'rest apis', 'javascript', 'git'], extra: ['docker', 'aws'],
    doingA: ['Build REST APIs with Node.js and Express.js', 'Work with MongoDB, JWT authentication and third-party integrations', 'Write clean, tested code and document endpoints'],
    doingB: ['Develop scalable Node.js services and background workers', 'Design MongoDB collections and indexes for fast queries', 'Add validation, logging and monitoring to production APIs'],
    needs: ['Good command of JavaScript and Node.js', 'Experience with Express.js, MongoDB and REST APIs', 'Familiarity with Git and Postman'],
  },
  mern: {
    skills: ['mongodb', 'express.js', 'react', 'node.js', 'javascript', 'rest apis', 'git'], extra: ['tailwind css', 'docker'],
    doingA: ['Build complete features across MongoDB, Express.js, React and Node.js', 'Design REST APIs and connect them to responsive React front ends', 'Deploy and debug applications together with the team'],
    doingB: ['Develop full-stack features on the MERN stack from database to UI', 'Implement JWT authentication, forms and dashboards', 'Write tests and review teammates’ code'],
    needs: ['Hands-on MERN stack projects (GitHub or a portfolio)', 'Good JavaScript, React and Node.js fundamentals', 'Understanding of REST APIs, JWT authentication and Git'],
  },
  fullstack: {
    skills: ['javascript', 'react', 'node.js', 'sql', 'rest apis', 'git'], extra: ['docker', 'aws'],
    doingA: ['Own features end to end: database, API and user interface', 'Build clean React front ends backed by Node.js services', 'Review code, write tests and help improve our delivery process'],
    doingB: ['Ship full-stack features across the React front end and the API layer', 'Design database tables and REST endpoints with the team', 'Debug production issues and improve performance end to end'],
    needs: ['Experience with JavaScript, React and a backend framework', 'Comfortable with SQL or MongoDB and REST API design', 'Familiar with Git, Docker basics and deployment'],
  },
  javascript: {
    skills: ['javascript', 'html', 'css', 'es6', 'git'], extra: ['react', 'node.js'],
    doingA: ['Write clean, modular JavaScript (ES6+) for web applications', 'Work with the DOM, APIs and modern tooling such as npm and Vite', 'Debug across browsers and improve performance'],
    doingB: ['Build interactive features in vanilla JavaScript and small frameworks', 'Integrate APIs and handle asynchronous code with async/await', 'Write maintainable code and small tests'],
    needs: ['Strong JavaScript fundamentals (closures, async/await, the DOM)', 'Knowledge of HTML, CSS and Git', 'Curiosity about frameworks like React'],
  },
  software: {
    skills: ['python', 'sql', 'git', 'data structures', 'rest apis'], extra: ['docker', 'aws'],
    doingA: ['Design, code and test features for our software products', 'Write maintainable code, unit tests and clear documentation', 'Take part in code reviews and sprint planning'],
    doingB: ['Develop and support business applications used by our clients', 'Fix defects, add features and improve existing code', 'Work with QA and product teams to deliver on time'],
    needs: ['Good programming fundamentals (data structures, OOP)', 'Working knowledge of Python or Java, SQL and Git', 'A problem-solving mindset and clear communication'],
  },
  analyst: {
    skills: ['sql', 'python', 'pandas', 'numpy', 'excel', 'power bi'], extra: ['tableau', 'statistics'],
    doingA: ['Clean and analyse data with SQL, Python (Pandas, NumPy) and Excel', 'Build dashboards and reports for business teams', 'Present insights in plain language'],
    doingB: ['Write SQL queries to answer questions from product and operations teams', 'Automate recurring reports with Python and Pandas', 'Track key metrics and flag trends early'],
    needs: ['Strong SQL and Excel skills', 'Basic Python with Pandas and NumPy', 'Analytical thinking and attention to detail'],
  },
  datasci: {
    skills: ['python', 'pandas', 'numpy', 'machine learning', 'scikit-learn', 'sql', 'data science'], extra: ['statistics', 'aws'],
    doingA: ['Build and evaluate machine learning models with Python (Pandas, NumPy, scikit-learn)', 'Explore data, engineer features and validate results', 'Work with engineers to move models into production'],
    doingB: ['Prepare datasets and experiment with machine learning approaches', 'Measure model performance and explain results to stakeholders', 'Document experiments so the team can reproduce them'],
    needs: ['Solid Python, statistics and machine learning basics', 'Experience with Pandas, NumPy and Jupyter notebooks', 'Ability to explain results to non-technical people'],
  },
  security: {
    skills: ['cybersecurity', 'owasp', 'linux', 'networking', 'vulnerability assessment', 'git'], extra: ['penetration testing', 'siem'],
    doingA: ['Monitor systems for threats and investigate security alerts', 'Run vulnerability scans and help fix issues using OWASP guidance', 'Document incidents and improve security processes'],
    doingB: ['Triage alerts from our monitoring tools and escalate real incidents', 'Test web applications against the OWASP Top 10', 'Write clear reports and recommendations for clients and developers'],
    needs: ['An understanding of cybersecurity fundamentals, networking and Linux', 'Knowledge of the OWASP Top 10 and common attack techniques', 'Curiosity, discipline and clear reporting skills'],
  },
  devops: {
    skills: ['linux', 'docker', 'aws', 'git', 'ci/cd'], extra: ['kubernetes', 'terraform'],
    doingA: ['Build and maintain CI/CD pipelines', 'Run services on AWS using Docker and Linux', 'Improve monitoring, reliability and release speed'],
    doingB: ['Automate deployments and environment setup', 'Manage cloud infrastructure, costs and access on AWS', 'Respond to incidents and write clear post-mortems'],
    needs: ['Hands-on Linux, Docker and Git', 'Experience with AWS and CI/CD tools', 'Scripting skills (Bash or Python) and a calm approach to incidents'],
  },
  qa: {
    skills: ['selenium', 'javascript', 'cypress', 'api testing', 'sql', 'git'], extra: ['jenkins', 'postman'],
    doingA: ['Design test cases and automate them with Selenium or Cypress', 'Test APIs and report defects with clear steps to reproduce', 'Work with developers to improve quality before release'],
    doingB: ['Write and maintain automated regression suites', 'Run exploratory and API tests before every release', 'Track defects and verify fixes'],
    needs: ['An understanding of testing concepts and the software lifecycle', 'Basics of Selenium or Cypress, JavaScript or Java, and SQL', 'A detail-oriented approach and good bug reports'],
  },
  uiux: {
    skills: ['figma', 'ui design', 'ux research', 'wireframing', 'prototyping', 'html', 'css'], extra: ['design systems'],
    doingA: ['Design wireframes, prototypes and polished screens in Figma', 'Run quick user research and usability tests', 'Collaborate with developers to ship designs faithfully'],
    doingB: ['Turn product ideas into clear user flows and interface designs', 'Build and maintain a consistent set of components in Figma', 'Test designs with real users and iterate'],
    needs: ['A portfolio showing UI/UX projects', 'Good knowledge of Figma and design principles', 'Basic HTML/CSS understanding is a plus'],
  },
};

const LEVEL = {
  fresher: {
    doing: 'Learn on the job through mentoring, pair programming and regular code reviews',
    needs: 'Freshers welcome: final-year students and recent graduates (B.E./B.Tech/BCA/MCA/B.Sc) can apply',
  },
  junior: {
    doing: 'Take ownership of well-defined features with support from senior teammates',
    needs: '1 to 2 years of relevant experience (projects and internships count)',
  },
  mid: {
    doing: 'Own features end to end and help review your teammates’ code',
    needs: '3+ years of professional experience',
  },
};

let index = 0;
const job = (companyKey, role, title, location, jobType, experienceYears, [min, max], about, skillsOverride) => {
  const i = index++;
  const template = ROLE[role];
  const level = experienceYears === 0 || jobType === 'internship' ? 'fresher' : experienceYears <= 2 ? 'junior' : 'mid';
  const perks = companyByKey[companyKey].perks.map((p) => `- ${p}`).join('\n');

  return {
    key: `IN${String(i + 1).padStart(2, '0')}`,
    company: companyKey,
    title,
    jobType,
    location,
    skills: skillsOverride ?? [...template.skills, ...(experienceYears >= 3 ? template.extra : [])],
    experienceYears,
    salary: [min, max, 'INR'],
    ...(i % 9 !== 8 && { deadlineDays: 14 + ((i * 7) % 46) }),
    postedDaysAgo: 1 + ((i * 5) % 30),
    description: `${describe({
      about,
      doing: [...(i % 2 ? template.doingB : template.doingA), LEVEL[level].doing],
      needs: [...template.needs, LEVEL[level].needs],
    })}\n\nWhat we offer\n${perks}\n\nLocation: ${location}`,
  };
};

const jobs = [
  job('codecrest', 'web', 'Web Developer', 'Andheri, Mumbai (Hybrid)', 'full-time', 1, [360000, 540000], 'Build fast, responsive websites for retail and education clients from our Andheri studio.'),
  job('codecrest', 'nodejs', 'Node.js Developer', 'Andheri, Mumbai (Hybrid)', 'full-time', 2, [650000, 950000], 'Join the backend team building booking and payment APIs that power our client applications.'),
  job('codecrest', 'mern', 'MERN Stack Developer', 'Navi Mumbai (On-site)', 'full-time', 1, [480000, 750000], 'Work across MongoDB, Express.js, React and Node.js on customer dashboards for logistics clients.'),
  job('codecrest', 'web', 'Junior Web Developer', 'Navi Mumbai (On-site)', 'full-time', 0, [300000, 420000], 'A friendly first job for graduates who enjoy turning designs into clean HTML, CSS and JavaScript.'),
  job('marinedrive', 'web', 'Web Developer (Fresher)', 'Powai, Mumbai (On-site)', 'full-time', 0, [280000, 400000], 'Learn modern web development on real client projects at our Powai studio, with a mentor from day one.'),
  job('marinedrive', 'react', 'React Developer', 'Powai, Mumbai (Hybrid)', 'full-time', 2, [800000, 1200000], 'Build component-driven React interfaces for fintech and media apps used by lakhs of people.'),
  job('marinedrive', 'uiux', 'UI/UX Designer', 'Mumbai, Maharashtra (Hybrid)', 'full-time', 2, [500000, 850000], 'Design clear, friendly product experiences and hand them to a team that cares about detail.'),
  job('marinedrive', 'web', 'Web Developer Intern', 'Andheri, Mumbai (Hybrid)', 'internship', 0, [120000, 216000], 'A six-month paid internship building landing pages and small features with HTML, CSS and JavaScript.'),
  job('nexora', 'react', 'React Developer', 'Pune, Maharashtra (Hybrid)', 'full-time', 1, [500000, 800000], 'Help build a project-management product used by remote teams across India and Europe.'),
  job('nexora', 'react', 'React Developer (Fresher)', 'Pune, Maharashtra (On-site)', 'full-time', 0, [320000, 480000], 'Start your React career in our Pune office with structured training and friendly code reviews.'),
  job('nexora', 'fullstack', 'Full Stack Developer', 'Pune, Maharashtra (Hybrid)', 'full-time', 3, [1000000, 1600000], 'Own features from database to UI in a small product team that ships every week.'),
  job('nexora', 'qa', 'QA Automation Tester', 'Pune, Maharashtra (Hybrid)', 'full-time', 2, [500000, 850000], 'Automate regression tests for a fast-moving SaaS product and keep releases calm.'),
  job('bluepeak', 'mern', 'MERN Stack Developer', 'Bangalore, Karnataka (Hybrid)', 'full-time', 2, [800000, 1300000], 'Build multi-tenant SaaS features on the MERN stack for customers in retail and healthcare.'),
  job('bluepeak', 'mern', 'MERN Stack Developer (Junior)', 'Bangalore, Karnataka (On-site)', 'full-time', 0, [450000, 700000], 'A junior MERN role with mentoring, pair programming and real ownership of small features.'),
  job('bluepeak', 'frontend', 'Frontend Developer', 'Bangalore, Karnataka (Hybrid)', 'full-time', 3, [1200000, 1900000], 'Lead the front end of our analytics dashboard with React, TypeScript and Tailwind CSS.'),
  job('bluepeak', 'devops', 'DevOps Engineer', 'Bangalore, Karnataka (Hybrid)', 'full-time', 4, [1800000, 2800000], 'Run our AWS platform and CI/CD pipelines, and make releases boring in the best way.'),
  job('marina', 'frontend', 'Frontend Developer', 'Chennai, Tamil Nadu (Hybrid)', 'full-time', 2, [600000, 1000000], 'Build accessible React interfaces for an e-learning platform with over 300,000 learners.'),
  job('marina', 'frontend', 'Frontend Developer (Fresher)', 'Chennai, Tamil Nadu (On-site)', 'full-time', 0, [300000, 450000], 'Kick-start your career on our Chennai front-end team with training in React and Tailwind CSS.'),
  job('marina', 'backend', 'Backend Developer (Python)', 'Chennai, Tamil Nadu (Hybrid)', 'full-time', 2, [700000, 1100000], 'Build Django REST services and data pipelines that power learning analytics.', ['python', 'django', 'sql', 'rest apis', 'git']),
  job('marina', 'javascript', 'JavaScript Developer', 'Chennai, Tamil Nadu (Hybrid)', 'full-time', 1, [400000, 650000], 'Write clean JavaScript for interactive lessons, quizzes and reporting screens.'),
  job('finhaven', 'datasci', 'Data Scientist', 'Hyderabad, Telangana (Hybrid)', 'full-time', 3, [1400000, 2400000], 'Build credit-risk and fraud-detection models on millions of transactions at our Hyderabad data hub.'),
  job('finhaven', 'datasci', 'Data Science Trainee', 'Hyderabad, Telangana (On-site)', 'full-time', 0, [350000, 500000], 'A structured six-month trainee programme for graduates who love Python, statistics and machine learning.'),
  job('finhaven', 'analyst', 'Data Analyst', 'Hyderabad, Telangana (Hybrid)', 'full-time', 1, [450000, 750000], 'Turn payments data into dashboards and insights for our risk, operations and product teams.'),
  job('finhaven', 'backend', 'Backend Developer', 'Hyderabad, Telangana (Hybrid)', 'full-time', 3, [1200000, 2000000], 'Design secure REST APIs and ledger services in Node.js for a growing payments platform.'),
  job('securenet', 'security', 'Cybersecurity Analyst', 'New Delhi (Hybrid)', 'full-time', 2, [600000, 1000000], 'Monitor client networks from our Delhi security operations centre and turn alerts into clear reports.'),
  job('securenet', 'security', 'Cybersecurity Analyst (Fresher)', 'New Delhi (On-site)', 'full-time', 0, [350000, 500000], 'Join our SOC training programme and learn threat monitoring, OWASP and incident response.'),
  job('securenet', 'security', 'Security Analyst', 'Delhi NCR (Hybrid)', 'full-time', 3, [900000, 1500000], 'Run vulnerability assessments and web-application security reviews for banking and government clients.'),
  job('securenet', 'devops', 'DevOps Engineer', 'New Delhi (Hybrid)', 'full-time', 4, [1500000, 2400000], 'Build secure, automated infrastructure on AWS and Linux for our managed-security platform.'),
  job('matrixbyte', 'software', 'Software Developer', 'Gurgaon, Haryana (Hybrid)', 'full-time', 2, [800000, 1300000], 'Build and maintain enterprise workflow software used by large insurers and banks.'),
  job('matrixbyte', 'fullstack', 'Full Stack Developer', 'Gurgaon, Haryana (Hybrid)', 'full-time', 4, [1500000, 2500000], 'Lead features across React front ends and Node.js services in a growing product team.'),
  job('matrixbyte', 'analyst', 'Data Analyst', 'Gurgaon, Haryana (Hybrid)', 'full-time', 1, [500000, 800000], 'Analyse customer and operations data with SQL and Python and present findings to leadership.'),
  job('matrixbyte', 'qa', 'QA Automation Tester', 'Gurgaon, Haryana (On-site)', 'full-time', 3, [800000, 1300000], 'Own automation for web and API tests using Selenium and Postman in a CI/CD-driven team.'),
  job('techtonic', 'fullstack', 'Full Stack Developer', 'Noida, Uttar Pradesh (Hybrid)', 'full-time', 2, [700000, 1200000], 'Build features end to end for an HR-tech product used by mid-size companies across India.'),
  job('techtonic', 'fullstack', 'Full Stack Developer (Fresher)', 'Noida, Uttar Pradesh (On-site)', 'full-time', 0, [350000, 520000], 'Learn full-stack development with React and Node.js in our Noida office, with a buddy and clear goals.'),
  job('techtonic', 'nodejs', 'Node.js Developer', 'Noida, Uttar Pradesh (Hybrid)', 'full-time', 2, [650000, 1000000], 'Build scalable APIs and background workers with Node.js, Express.js and MongoDB.'),
  job('techtonic', 'software', 'Software Developer', 'Noida, Uttar Pradesh (On-site)', 'full-time', 1, [400000, 650000], 'Develop and test features for our product suite with a supportive engineering team.'),
  job('pixelbay', 'web', 'Web Developer', 'Ahmedabad, Gujarat (On-site)', 'full-time', 1, [300000, 480000], 'Build clean, fast websites and small web apps for D2C brands and manufacturers.'),
  job('pixelbay', 'uiux', 'UI/UX Designer', 'Ahmedabad, Gujarat (Hybrid)', 'part-time', 1, [360000, 600000], 'Design website and app screens three days a week, alongside our small, friendly team.'),
  job('pixelbay', 'frontend', 'Frontend Developer', 'Ahmedabad, Gujarat (Hybrid)', 'full-time', 2, [500000, 850000], 'Turn our designers’ work into fast React front ends with Tailwind CSS.'),
  job('pixelbay', 'javascript', 'JavaScript Developer', 'Ahmedabad, Gujarat (On-site)', 'full-time', 1, [400000, 650000], 'Write interactive JavaScript for e-commerce storefronts and internal tools.'),
  job('pinkcity', 'web', 'Web Developer', 'Jaipur, Rajasthan (On-site)', 'full-time', 0, [240000, 360000], 'A great first web-developer job: build client sites with HTML, CSS and JavaScript and learn from seniors.'),
  job('pinkcity', 'mern', 'MERN Stack Developer', 'Jaipur, Rajasthan (Hybrid)', 'full-time', 2, [600000, 1000000], 'Build tourism and hospitality platforms on the MERN stack for clients across Rajasthan.'),
  job('pinkcity', 'backend', 'Backend Developer', 'Jaipur, Rajasthan (Hybrid)', 'full-time', 3, [800000, 1300000], 'Design APIs and databases for booking and inventory systems used by hotels and travel companies.'),
  job('pinkcity', 'software', 'Software Developer Intern', 'Jaipur, Rajasthan (On-site)', 'internship', 0, [96000, 180000], 'A paid six-month internship for final-year students to learn software development on live projects.'),
  job('hooghly', 'fullstack', 'Full Stack Developer', 'Kolkata, West Bengal (Hybrid)', 'full-time', 2, [600000, 1000000], 'Build storefront and seller tools for an e-commerce marketplace serving eastern India.'),
  job('hooghly', 'analyst', 'Data Analyst', 'Kolkata, West Bengal (Hybrid)', 'full-time', 1, [400000, 650000], 'Analyse orders, returns and delivery data to help sellers grow and cut costs.'),
  job('hooghly', 'software', 'Software Developer', 'Kolkata, West Bengal (On-site)', 'full-time', 3, [800000, 1300000], 'Improve our order-management platform with clean, well-tested code in a friendly team.'),
  job('hooghly', 'qa', 'QA Automation Tester (Fresher)', 'Kolkata, West Bengal (On-site)', 'full-time', 0, [300000, 450000], 'Learn test automation with Selenium and Cypress while protecting our checkout flow.'),
  job('tricity', 'nodejs', 'Node.js Developer', 'Chandigarh (Hybrid)', 'full-time', 2, [600000, 950000], 'Build REST APIs and real-time features with Node.js for our health and fitness apps.'),
  job('tricity', 'frontend', 'Frontend Developer', 'Chandigarh (On-site)', 'full-time', 1, [400000, 650000], 'Build responsive React interfaces for web and mobile web with a design-focused team.'),
  job('tricity', 'datasci', 'Data Scientist', 'Chandigarh (Hybrid)', 'contract', 2, [900000, 1500000], 'A 12-month contract building recommendation and forecasting models with Python.'),
  job('tricity', 'security', 'Cybersecurity Analyst', 'Chandigarh (On-site)', 'full-time', 2, [550000, 900000], 'Protect our apps and customer data: vulnerability scans, log monitoring and secure-code reviews.'),
  job('chinar', 'web', 'Web Developer', 'Srinagar, Kashmir (On-site)', 'full-time', 0, [240000, 360000], 'Build websites and web tools for tourism, handicraft and education clients across Kashmir.'),
  job('chinar', 'react', 'React Developer', 'Srinagar, Kashmir (Hybrid)', 'full-time', 1, [400000, 650000], 'Build React front ends for our e-commerce and learning products with a small, close-knit team.'),
  job('chinar', 'software', 'Software Developer', 'Srinagar, Kashmir (On-site)', 'full-time', 1, [360000, 560000], 'Develop and support business software for clients, with training and mentoring on the job.'),
  job('chinar', 'uiux', 'UI/UX Designer (Fresher)', 'Srinagar, Kashmir (On-site)', 'full-time', 0, [240000, 400000], 'Start your design career with wireframes, prototypes and usability tests for real products.'),
  job('anywhere', 'fullstack', 'Full Stack Developer', 'Remote (India)', 'full-time', 3, [1200000, 2000000], 'Work from anywhere in India on a remote-first product team with async communication.'),
  job('anywhere', 'react', 'React Developer', 'Remote (India)', 'full-time', 2, [900000, 1500000], 'Build polished React interfaces for international SaaS customers from your own desk.'),
  job('anywhere', 'devops', 'DevOps Engineer', 'Remote (India)', 'contract', 3, [1400000, 2400000], 'A six-month remote contract improving CI/CD pipelines and cloud costs on AWS.'),
  job('anywhere', 'backend', 'Backend Developer (Node.js)', 'Remote (India)', 'freelance', 2, [800000, 1400000], 'Freelance backend work on Node.js APIs with flexible hours and monthly milestones.'),
];

module.exports = { companies, jobs };
